spring:
  datasource:
    url: jdbc:mysql://39.107.102.246:3306/mmall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: nic
    password: dy@980302

mybatis:
  mapper-locations: classpath:/mapper/**.xml