package com.dy.mmall.dao;

import com.dy.mmall.bean.Category;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Mon Mar 25 17:10:44 CST 2019
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_category
     *
     * @mbg.generated Mon Mar 25 17:10:44 CST 2019
     */
    int insertSelective(Category record);
}