package com.dy.mmall.dao;

import com.dy.mmall.bean.PayInfo;

public interface PayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 25 17:10:44 CST 2019
     */
    int insert(PayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbg.generated Mon Mar 25 17:10:44 CST 2019
     */
    int insertSelective(PayInfo record);
}