package com.dy.mmall.dao;

import com.dy.mmall.bean.Shipping;

public interface ShippingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Mon Mar 25 17:10:44 CST 2019
     */
    int insert(Shipping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbg.generated Mon Mar 25 17:10:44 CST 2019
     */
    int insertSelective(Shipping record);
}