package com.dy.mmall.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;

@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.id
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.username
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.password
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    @JsonIgnore
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.email
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.phone
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.question
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    @JsonIgnore
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.answer
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    @JsonIgnore
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.role
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.create_time
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_user.update_time
     *
     * @mbg.generated Mon Mar 18 16:37:36 CST 2019
     */
    private Date updateTime;
}